# Generated by Django 2.2.10 on 2021-07-14 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0004_auto_20210714_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
